version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/app/deploy
permissions:
  - object: /home/ubuntu/app/deploy
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/clean-up.sh  # clean-up.sh 파일 경로
      timeout: 180

  AfterInstall:
    - location: scripts/start.sh  # 기존 start.sh 파일 경로
      timeout: 180
