version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/app/deploy

permissions:
  - object: /home/ubuntu/app/deploy
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: deploy/clean-up.sh  # deploy 폴더 안에 있는 걸로 고쳐야 함
      timeout: 180

  AfterInstall:
    - location: deploy/start.sh     # 이것도 deploy/start.sh로
      timeout: 180
