name: Deploy Spring Boot to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give gradlew permission
        run: chmod +x ./gradlew

      - name: Build with Gradle (prod profile)
        run: ./gradlew clean build -Dspring.profiles.active=prod
        
      - name: Generate JaCoCo Test Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Rename jar for deployment
        run: mv build/libs/*.jar build/libs/app.jar

      - name: Prepare deploy-package directory
        run: |
          rm -rf deploy-package
          mkdir -p deploy-package
          cp appspec.yml deploy-package/
          cp start.sh deploy-package/
          cp clean-up.sh deploy-package/
          cp build/libs/app.jar deploy-package/

      - name: Give execution permission to scripts
        run: chmod +x deploy-package/start.sh deploy-package/clean-up.sh

      - name: Zip for deployment
        run: |
          cd deploy-package
          zip -r ../app.zip ./*

      - name: Upload to S3
        run: aws s3 cp app.zip s3://switching-bucket-202504/app.zip
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name "switching-ec2-app" \
            --deployment-group-name "switching-deploy-group" \
            --revision "revisionType=S3,s3Location={bucket=switching-bucket-202504,key=app.zip,bundleType=zip}" \
            --deployment-config-name "CodeDeployDefault.AllAtOnce"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
