name: Deploy Spring Boot to AWS

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ GitHub에서 코드 가져오기
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Java 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 3️⃣ Gradle 빌드 (JAR 파일 생성)
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
