name: Deploy Spring Boot to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give gradlew permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Rename jar for deployment
        run: mv build/libs/*.jar build/libs/app.jar

      - name: Copy deploy files to root
        run: |
          cp build/libs/app.jar ./
          cp start.sh ./
          cp clean-up.sh ./
          cp appspec.yml ./

      - name: Zip deployment package
        run: zip -r app.zip app.jar start.sh clean-up.sh appspec.yml

      - name: Upload to S3
        run: aws s3 cp app.zip s3://switching-bucket-202504/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
