name: Deploy Spring Boot to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give gradlew permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Rename jar for deployment
        run: mv build/libs/*.jar build/libs/app.jar

      - name: Prepare deploy-package directory
        run: |
          rm -rf deploy-package
          mkdir -p deploy-package
          cp appspec.yml deploy-package/
          cp start.sh deploy-package/
          cp clean-up.sh deploy-package/
          cp build/libs/app.jar deploy-package/

      - name: Zip for deployment
        run: |
          cd deploy-package
          zip -r ../app.zip ./*

      - name: Upload to S3
        run: aws s3 cp app.zip s3://switching-bucket-202504/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name "switching-ec2-app" \
            --deployment-group-name "switching-deploy-group" \
            --revision type=S3,bucket=switching-bucket-202504,key=app.zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "Deploy triggered by GitHub Actions" \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
